issues:
  exclude-use-default: false

linters:
  enable-all: true
  disable:
    # Linters that are deprecated.
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

    # Linters that are not used for this project.
    - wrapcheck
    - depguard

linters-settings:
  goheader:
    template: |-
      Copyright Josh Komoroske. All rights reserved.
      Use of this source code is governed by the MIT license,
      a copy of which can be found in the LICENSE.txt file.
      SPDX-License-Identifier: MIT
