name: Commitlint
on: pull_request

jobs:
  lint:
    name: Commitlint
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5
