name: GolangCI-Lint
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  lint:
    name: GolangCI-Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: golangci/golangci-lint-action@v3
        with:
          # https://github.com/golangci/golangci-lint/releases/tag/v1.55.2
          version: v1.55.2
